services:
  api:
    build: .
    image: housing-api:latest
    container_name: housing-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PRED_LOG_PATH=/app/data/predictions.csv
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: housing-redis
    # ports:
    #   - "6379:6379"
